# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shoulders < Formula
  desc "CLI for the Shoulders Internal Developer Platform"
  homepage "https://github.com/jherreros/shoulders"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jherreros/shoulders/releases/download/v0.2.2/shoulders_0.2.2_darwin_amd64.tar.gz"
      sha256 "ba3c1702e48adff378cb8b7e21bb4f2a907fdfe03aa00ae3018372b5410c73f0"

      define_method(:install) do
        bin.install "shoulders"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jherreros/shoulders/releases/download/v0.2.2/shoulders_0.2.2_darwin_arm64.tar.gz"
      sha256 "746bb6cd8e89d068dad3101d1cb9dbfa09a09a0992a4aab0990ac566a76c0b46"

      define_method(:install) do
        bin.install "shoulders"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jherreros/shoulders/releases/download/v0.2.2/shoulders_0.2.2_linux_amd64.tar.gz"
      sha256 "6064290137c5c02f2d0fe01a640c8754572a28223e6ffc658d3f94d59fe0c0f4"
      define_method(:install) do
        bin.install "shoulders"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jherreros/shoulders/releases/download/v0.2.2/shoulders_0.2.2_linux_arm64.tar.gz"
      sha256 "32105d5c3a95a9dd1eb562f1535eac6cf4a8ba65231a0772416990dd5ef9756e"
      define_method(:install) do
        bin.install "shoulders"
      end
    end
  end

  test do
    system "#{bin}/shoulders", "--version"
  end
end
