# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shoulders < Formula
  desc "CLI for the Shoulders Internal Developer Platform"
  homepage "https://github.com/jherreros/shoulders"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jherreros/shoulders/releases/download/v0.2.3/shoulders_0.2.3_darwin_amd64.tar.gz"
      sha256 "9446cf81d9a4e58b0c5a9bf269711df250d5e394d746f33de74bc1b2d25a77aa"

      define_method(:install) do
        bin.install "shoulders"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jherreros/shoulders/releases/download/v0.2.3/shoulders_0.2.3_darwin_arm64.tar.gz"
      sha256 "ef9cbc307a3acebf1a86c92e9aad74f6d44649b56252a0fcc594eaaaea15c819"

      define_method(:install) do
        bin.install "shoulders"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jherreros/shoulders/releases/download/v0.2.3/shoulders_0.2.3_linux_amd64.tar.gz"
      sha256 "fe80a6f6182e97c30b9f3806b1b23c3e7f346e367782683d73b7fbbf12bd1593"
      define_method(:install) do
        bin.install "shoulders"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jherreros/shoulders/releases/download/v0.2.3/shoulders_0.2.3_linux_arm64.tar.gz"
      sha256 "430578b7ef9514c4fddba4c34f09550cec2ab021d10a679b98cd9aa9d0fe4914"
      define_method(:install) do
        bin.install "shoulders"
      end
    end
  end

  test do
    system "#{bin}/shoulders", "--version"
  end
end
